name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"

      - name: Use Node.js v22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run ESLint
        run: yarn lint --fix=false

  Testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 24]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run tests
        run: yarn test --coverage

      - name: Store code coverage report
        uses: actions/upload-artifact@v4
        if: matrix.node == 22
        with:
          name: coverage
          path: coverage/

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"

      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Code
        run: yarn build
